---
- name: show version command from console using SmartCS
  hosts: smartcs
  gather_facts: no
  
  vars:
  #ttynoはユーザごとに異なります。Playbook作成時に変更してください。
  - ansible_connection: network_cli
  - ansible_network_os: smartcs
  - ttyno: '1'
  
  tasks:
  - name: show version 
    smartcs_tty_command:
      tty: '{{ ttyno }}'
      recvchar:
      - 'login: '
      - '> '
      sendchar:
      - 'operator'
      - 'show version'
      - 'exit'
