---
- name: show version command from console using SmartCS
  hosts: smartcs
  gather_facts: no
  
  vars:
  ### Variables that NEED to Change ###
  - tty_no: '1'

  ### Variables that should NOT change ###
  - ansible_connection: network_cli
  - ansible_network_os: smartcs
  
  tasks:
  - name: show version 
    smartcs_tty_command:
      tty: '{{ tty_no }}'
      recvchar:
      - 'login: '
      - '> '
      sendchar:
      - 'operator'
      - 'show version'
      - 'exit'
