---
- name: ansible-reach settings from console using SmartCS
  hosts: smartcs
  gather_facts: no 

  vars:
  ### Variables that NEED to Change ###
  - tty_no: '1'
  - ax_ipaddr: '192.168.128.2'

  ### Variables that should NOT change ###
  - ansible_connection: network_cli
  - ansible_network_os: smartcs
  
  - ax_user: 'alaxala'
  - ax_password: 'secret2230'
  - ax_subnet: '255.255.255.0'
  - ax_gateway: '192.168.128.254'

  tasks:
  - name: setting ipaddr and ssh
    smartcs_tty_command:
      tty: '{{ tty_no }}'
      custom_response: on
      custom_response_delete_nl: on
      recvchar:
      - 'login: '
      - 'Password:'
      - '> '
      - '# '
      - '(config)# '
      - '!(config)# '
      - '!(config-line)# '
      - '!(config-if)# '
      sendchar:
      - '{{ ax_user }}'
      - '{{ ax_password }}'
      - 'enable'
      - '{{ ax_password }}'
      - 'configure'
      - 'interface vlan 1'
      - 'ip address {{ ax_ipaddr }} {{ ax_subnet }}'
      - 'exit'
      - 'ip route 0.0.0.0 0.0.0.0 {{ ax_gateway }}'
      - 'ip ssh'
      - 'line vty 0 1'
      - 'transport input ssh'
      - 'save'
      - 'exit'
      - 'exit'
      - 'exit'
    register: result

  - name: 'register stdout_lines_custom'
    debug:
      msg: '{{ result.stdout_lines_custom }}'
