---
- name: user settings from console using SartCS
  hosts: smartcs
  gather_facts: no
  
  vars:
  ### Variables that NEED to Change ###
  - tty_no: '1'

  ### Variables that should NOT change ###
  - ansible_connection: network_cli
  - ansible_network_os: smartcs
  
  - ax_init_user: 'operator'
  - ax_user: 'alaxala'
  - ax_password: 'secret2230'

  tasks:
  - name: rename login user and setting password
    smartcs_tty_command:
      tty: '{{ tty_no }}'
      custom_response: on
      custom_response_delete_nl: on
      recvchar:
      - 'login: '
      - 'Password: '
      - 'Old username:'
      - 'New username:'
      - 'New password:'
      - 'Retype new password:'
      - '> '
      - '# '
      - '!# '
      sendchar:
      - '{{ ax_init_user }}'
      - 'enable'
      - 'rename user'
      - '{{ ax_init_user }}'
      - '{{ ax_user }}'
      - 'password'
      - '{{ ax_password }}'
      - '{{ ax_password }}'
      - 'password enable-mode'
      - '{{ ax_password }}'
      - '{{ ax_password }}'
      - 'exit'
