---
- name: ansible-reach settings from console using SmartCS
  hosts: smartcs
  gather_facts: no 

  vars:
  #ipaddr、ttynoはユーザごとに異なります。Playbook作成時に変更してください。
  - ansible_connection: network_cli
  - ansible_network_os: smartcs
  - username: 'alaxala'
  - password: 'secret2230'
  - ipaddr: '192.168.128.2'
  - subnet: '255.255.255.0'
  - gateway: '192.168.128.254'
  - ttyno: '1'

  tasks:
  - name: setting ipaddr and ssh
    smartcs_tty_command:
      tty: '{{ ttyno }}'
      custom_response: on
      custom_response_delete_nl: on
      recvchar:
      - 'login: '
      - 'Password:'
      - '> '
      - '# '
      - '(config)# '
      - '!(config)# '
      - '!(config-line)# '
      - '!(config-if)# '
      sendchar:
      - '{{ username }}'
      - '{{ password }}'
      - 'enable'
      - '{{ password }}'
      - 'configure'
      - 'interface vlan 1'
      - 'ip address {{ ipaddr }} {{ subnet }}'
      - 'exit'
      - 'ip route 0.0.0.0 0.0.0.0 {{ gateway }}'
      - 'ip ssh'
      - 'line vty 0 1'
      - 'transport input ssh'
      - 'save'
      - 'exit'
      - 'exit'
      - 'exit'
    register: result

  - name: 'register stdout_lines_custom'
    debug:
      msg: '{{ result.stdout_lines_custom }}'
