---
- name: user settings from console using SartCS
  hosts: smartcs
  gather_facts: no
  
  vars:
  #ttynoはユーザごとに異なります。Playbook作成時に変更してください。
  - ansible_connection: network_cli
  - ansible_network_os: smartcs
  - inituser: 'operator'
  - username: 'alaxala'
  - password: 'secret2230'
  - ttyno: '1'

  tasks:
  - name: rename login user and setting password
    smartcs_tty_command:
      tty: '{{ ttyno }}'
      custom_response: on
      custom_response_delete_nl: on
      recvchar:
      - 'login: '
      - 'Password: '
      - 'Old username:'
      - 'New username:'
      - 'New password:'
      - 'Retype new password:'
      - '> '
      - '# '
      - '!# '
      sendchar:
      - '{{ inituser }}'
      - 'enable'
      - 'rename user'
      - '{{ inituser }}'
      - '{{ username }}'
      - 'password'
      - '{{ password }}'
      - '{{ password }}'
      - 'password enable-mode'
      - '{{ password }}'
      - '{{ password }}'
      - 'exit'
