---
- name: add acl configration
  hosts: ios_sshxpt
  gather_facts: no

  vars:
  - EC2_Global_ipaddr: "{{ hostvars['ansible']['ansible_host'] }}"
  - Cat3550_ipaddr: "{{ hostvars['ios']['ansible_host'] }}"

  tasks:
  - name: configure access list
    cisco.ios.ios_acls:
      config:
      - afi: ipv4
        acls:
        - name: access_ansible_host_only
          acl_type: extended
          aces:
          - sequence: 10
            grant: permit
            protocol_options:
              ip: yes
            source:
              host: "{{ EC2_Global_ipaddr }}"
            destination:
              host: "{{ Cat3550_ipaddr }}"
          - sequence: 20
            grant: deny
            protocol_options:
              ip: yes
            source:
              any: yes
            destination:
              any: yes
      state: merged

  - name: set access-list to interface
    cisco.ios.ios_acl_interfaces:
      config:
      - name: Vlan1
        access_groups:
        - afi: ipv4
          acls:
          - name: access_ansible_host_only
            direction: in
      state: merged