---
- name: gathering ios informataion from console using SmartCS
  hosts: ios_sshxpt
  gather_facts: no

  tasks:
  - name: show commands
    cisco.ios.ios_command:
      commands:
        - show version
        - show interfaces gigabitethernet 0/1
        - show ip interface
        - show vlan
        - show running-config
    register: result

  - name: show command output
    debug:
      msg:
        - '{{ result.stdout_lines[0] }}'