---
- name: ansible-reach settings from console using SmartCS
  hosts: smartcs
  gather_facts: no

  vars:
  - tty_no: "{{ hostvars['ios']['smartcs_tty'] }}"
  - ios_ipaddr: "{{ hostvars['ios']['ansible_host'] }}"
  - ios_user: "{{ hostvars['ios']['ansible_user'] }}"
  - ios_password: "{{ hostvars['ios']['ansible_password'] }}"

  - ios_subnet: '255.255.255.0'
  - ios_gateway: '192.168.128.254'

  tasks:
  - name: setting ipaddr and ssh
    seiko.smartcs.smartcs_tty_command:
      tty: "{{ tty_no }}"
      custom_response: on
      custom_response_delete_nl: on
      error_detect_on_module: failed
      recvchar:
      - 'Switch>'
      - 'Switch#'
      - 'Switch(config)#'
      - 'Switch(config-if)#'
      - 'Switch(config-line)#'
      - 'Press RETURN to get started.'
      - 'Username: '
      - 'Password: '
      - 'How many bits in the modulus [512]: '
      - 'Destination filename [startup-config]?'
      sendchar:
      - '__NL__'
      - 'cisco'
      - '{{ ios_password }}'
      - 'enable'
      - '{{ ios_password }}'
      - 'configure terminal'
      - 'interface vlan1'
      - 'ip address {{ ios_ipaddr }} {{ ios_subnet }}'
      - 'no shutdown'
      - 'exit'
      - 'ip default-gateway {{ ios_gateway }}'
      - 'line vty 0 1'
      - 'login local'
      - 'transport input ssh'
      - 'exit'
      - 'ip domain-name cisco'
      - 'crypto key generate rsa'
      - '1024'
      - 'exit'
      - 'copy running-config startup-config'
      - '__NL__'
      - 'exit'
    register: result

  - name: 'register stdout_lines_custom'
    debug:
      msg: '{{ result.stdout_lines_custom }}'