---
- name: gathering configration from console using SmartCS
  hosts: smartcs
  
  vars:
  ### Variables that NEED to Change ###
  - ansible_user: "port01"
  - ansible_password: "secret01"
  - ansible_port: 9301
 
  ### Variables that should NOT change ###
  - ansible_connection: network_cli
  - ansible_network_os: ax
  
  - ansible_become: yes
  - ansible_become_method: enable
  - ansible_become_pass: 'secret2230'

  tasks:
  - name: show commands
    ax_command:
      commands:
        - show ip interface
        - show vlan
        - show access-filter
        - show running-config
