---
- name: ax f/w update from console using SmartCS
  hosts: smartcs
  gather_facts: no
  
  vars:
  ### Variables that NEED to Change ###
  - tty_no: '1'
  
  - ftp_server: '192.168.127.2'
  - ftp_user: 'rhel01'
  - ftp_password: 'secret01'
  - fwimg_path: '/home/rhel01'
  
  ### Variables that should NOT change ###
  - ansible_connection: network_cli
  - ansible_network_os: smartcs
  - ansible_command_timeout: 300
  
  - ax_user: 'alaxala'
  - ax_password: 'secret2230'
  - verupimg: 'AX2230L20210-01.bin'

  tasks:
  - name: ax ppupdate 
    smartcs_tty_command:
      tty: '{{ tty_no }}'
      cmd_timeout: 180
      custom_response: on
      custom_response_delete_nl: on
      recvchar:
      - 'login:'
      - 'Password:'
      - '> '
      - '# '
      - 'Name:'
      - 'ftp> '
      - 'Do you wish to continue? (y/n)'
      sendchar:
      - '{{ ax_user }}'
      - '{{ ax_password }}'
      - 'show version'
      - 'enable'
      - '{{ ax_password }}'
      - 'ftp {{ ftp_server }}'
      - '{{ ftp_user }}'
      - '{{ ftp_password }}'
      - 'binary'
      - 'cd {{ fwimg_path }}'
      - 'get {{ verupimg }} k.img'
      - 'bye'
      - 'ppupdate ramdisk k.img'
      - 'y'
      - '{{ ax_user }}'
      - '{{ ax_password }}'
      - 'show version'
      - 'exit'
    register: result
  
  - name: before/after version and reboot process
    debug:
      msg: 
        - '{{ result.stdout_lines_custom[2].response }}'
        - '{{ result.stdout_lines_custom[12].response }}'
        - '{{ result.stdout_lines_custom[13].response }}'
        - '{{ result.stdout_lines_custom[16].response }}'
