---
- name: initializing user settings
  hosts: smartcs
  gather_facts: no
  
  vars:
  #ttynoはユーザごとに異なります。Playbook作成時に変更してください。
  - ansible_connection: network_cli
  - ansible_network_os: smartcs
  - inituser: 'operator'
  - username: 'alaxala'
  - password: 'secret2230'
  - ttyno: '1'
  
  tasks:
  - name: "smartcs_tty_command"
    smartcs_tty_command:
      tty: '{{ ttyno }}'
      custom_response: on
      custom_response_delete_nl: on
      recvchar:
      - 'login:'
      - 'Password:'
      - 'Old username:'
      - 'New username:'
      - '> '
      - '# '
      sendchar:
      - '{{ username }}'
      - '{{ password }}'
      - 'enable'
      - '{{ password }}'
      - 'clear password'
      - 'clear password enable-mode'
      - 'rename user'
      - '{{ username }}'
      - '{{ inituser }}'
      - 'exit'
