---
- name: initializing user settings
  hosts: smartcs
  gather_facts: no
  
  vars:
  ### Variables that NEED to Change ###
  - tty_no: '1'

  ### Variables that should NOT change ###
  - ansible_connection: network_cli
  - ansible_network_os: smartcs
  
  - ax_init_user: 'operator'
  - ax_user: 'alaxala'
  - ax_password: 'secret2230'
  
  tasks:
  - name: "smartcs_tty_command"
    smartcs_tty_command:
      tty: '{{ tty_no }}'
      custom_response: on
      custom_response_delete_nl: on
      recvchar:
      - 'login:'
      - 'Password:'
      - 'Old username:'
      - 'New username:'
      - '> '
      - '# '
      sendchar:
      - '{{ ax_user }}'
      - '{{ ax_password }}'
      - 'enable'
      - '{{ ax_password }}'
      - 'clear password'
      - 'clear password enable-mode'
      - 'rename user'
      - '{{ ax_user }}'
      - '{{ ax_init_user }}'
      - 'exit'
