---
- name: add vlan for ios config
  hosts: ios
  gather_facts: no

  vars:
  - ansible_command_timeout: 60
  
  - vid: '2000'
  - ipaddr: '192.168.0.1'
  - netmask: '255.255.255.0'
  - portif : '0/2'

  tasks:
  - name: configure vlan
    cisco.ios.ios_config:
      lines:
      - vlan "{{ vid }}"
  
  - name: configure interface vlan <vid>
    cisco.ios.ios_config:
      lines:
      - ip address "{{ ipaddr }}" "{{ netmask }}"
      parents: interface vlan "{{ vid }}"
  
  - name: vlan configuration to port
    cisco.ios.ios_config:
      lines:
      - switchport mode trunk
      - switchport trunk allowed vlan add {{ vid }}
      parents: interface GigabitEthernet {{ portif }}
      save_when: modified