---
- name: user settings from console using SartCS
  hosts: smartcs
  gather_facts: no
  
  vars:
  - tty_no: "{{ hostvars['ios']['smartcs_tty'] }}"  
  - ios_user: "{{ hostvars['ios']['ansible_user'] }}"
  - ios_password: "{{ hostvars['ios']['ansible_password'] }}"

  tasks:
  - name: rename login user and setting password
    seiko.smartcs.smartcs_tty_command:
      tty: "{{ tty_no }}"
      custom_response: on
      custom_response_delete_nl: on
      recvchar:
      - "started."
      - "Switch1>"
      - "Switch1#"
      - "Switch1(config)#"
      - "Password: "
      sendchar:
      - __NL__
      - enable
      - cisco
      - configure terminal
      - username {{ ios_user }} password {{ ios_password }}
      - enable password {{ ios_password }}
      - exit
      - exit