---
- name: save show commands output to localfile
  hosts: ios
  gather_facts: no

  vars:
  - os_version: "12.2"

  tasks:
  - name: execute show commands
    cisco.ios.ios_command:
      commands:
        - show version
    register: result
  
  - name: check Software version
    assert:
      that: "'{{ os_version }}' in '{{ result.stdout_lines[0][0] }}'"
      fail_msg: "ios Software Version is not '{{ os_version }}'"