---
- name: Login from Console using SmartCS
  hosts: smartcs
  gather_facts: no
  
  vars:
  - tty_no: "{{ hostvars['ios']['smartcs_tty'] }}"
  
  - ansible_command_timeout: 60

  tasks:
  - name: login cat3550
    seiko.smartcs.smartcs_tty_command:
      tty: '{{ tty_no }}'
      recvchar:
      - "started."
      sendchar:
      - __NL__