---
- name: gathering configration from console using SmartCS
  hosts: ios_sshxpt
  gather_facts: no

  tasks:
  - name: show commands
    cisco.ios.ios_command:
      commands:
        - show ip interface
        - show vlan
        - show running-config