---
- name: set initial configuration from console using SmartCS
  hosts: ios_sshxpt
  gather_facts: no
  
  vars:  
  - ios_ipaddr: "{{ hostvars['ios']['ansible_host'] }}"  
  - ios_subnet: '255.255.255.0'

  tasks:
  - name: set ipaddr to intarface vlan 1
    cisco.ios.ios_config:
      lines:
        - 'ip address {{ ios_ipaddr }} {{ ios_subnet }}'
      parents: interface vlan 1
      save_when: changed
  
  - name: intarface up
    cisco.ios.ios_config:
      lines:
        - 'no shutdown'
      parents: interface gigabitethernet 0/1
      save_when: changed
  
  - name: enable ssh 
    cisco.ios.ios_config:
      lines:
        - 'line vty 0 1'
        - 'transport input ssh'
      #parents: line vty 0 1
      save_when: changed