---
- name: initializing settings
  hosts: smartcs
  gather_facts: no
  
  vars:
  - tty_no: "{{ hostvars['ios']['smartcs_tty'] }}" 
  - ios_password: "{{ hostvars['ios']['ansible_password'] }}"
  
  tasks:
  - name: "smartcs_tty_command"
    seiko.smartcs.smartcs_tty_command:
      tty: '{{ tty_no }}'
      custom_response: on
      custom_response_delete_nl: on
      error_detect_on_module: failed
      recvchar:
      - 'Username: '
      - 'Cat3550>'
      - 'Cat3550#'
      - 'Password: '
      - 'Erasing the nvram filesystem will remove all configuration files! Continue? [confirm]'
      - 'Delete filename [vlan.dat]?'
      - 'Delete flash:vlan.dat? [confirm]'
      - 'Proceed with reload? [confirm]'
      sendchar:
      - '__NL__'
      - 'cisco'
      - '{{ ios_password }}'
      - 'enable'
      - '{{ ios_password }}'
      - 'write erase'
      - '__NL__'
      - 'delete flash:vlan.dat'
      - '__NL__'
      - '__NL__'
      - 'reload'
      - '__NL____NOWAIT__'