---
- name: initializing user settings
  hosts: smartcs
  gather_facts: no
  
  vars:
  - tty_no: "{{ hostvars['ios']['smartcs_tty'] }}" 
  
  tasks:
  - name: "smartcs_tty_command"
    seiko.smartcs.smartcs_tty_command:
      tty: '{{ tty_no }}'
      custom_response: on
      custom_response_delete_nl: on
      recvchar:
      - "started."
      - "Switch1>"
      - "Switch1#"
      - "Password: "
      - "Erasing the nvram filesystem will remove all configuration files! Continue? [confirm]"
      - "Delete filename [vlan.dat]?"
      - "Delete flash:vlan.dat? [confirm]"
      - "Proceed with reload? [confirm]"
      sendchar:
      - __NL__
      - enable
      - secret3550
      - erase startup-config
      - __NL__
      - delete flash:vlan.dat
      - __NL__
      - __NL__
      - reload
      - __NL__
      
